if(CODE_COVERAGE)
    message("Coverage build")
    if(CMAKE_COMPILER_IS_GNUCXX)
        include(${CMAKE_CURRENT_SOURCE_DIR}/../toolchains/lcovCoverage.cmake)
    message("Building with lcov code coverage tools")
    elseif("${CMAKE_C_COMPILER_ID}" MATCHES "(Apple)?[Cc]lang" OR
           "${CMAKE_CXX_COMPILER_ID}" MATCHES "(Apple)?[Cc]lang")
           message("Building with llvm code coverage tools")
           include(${CMAKE_CURRENT_SOURCE_DIR}/../toolchains/llvmCoverage.cmake)
    endif()
    include(${CMAKE_CURRENT_SOURCE_DIR}/../toolchains/cglTests.cmake)
else()
    message("Normal build")
    include(${CMAKE_CURRENT_SOURCE_DIR}/../toolchains/cglBuild.cmake)
endif()